// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto.Models;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20231112060106_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyecto.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("f5122a67-dc4c-491c-ae01-4408e4841945"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("f5122a67-dc4c-491c-ae01-4408e4841902"),
                            Nombre = "Actividades Personales",
                            Peso = 10
                        });
                });

            modelBuilder.Entity("proyecto.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("f5122a67-dc4c-491c-ae01-4408e4841945"),
                            CategoriaId = new Guid("f5122a67-dc4c-491c-ae01-4408e4841945"),
                            FechaCreacion = new DateTime(2023, 11, 12, 0, 1, 6, 284, DateTimeKind.Local).AddTicks(1279),
                            PrioridadTarea = 1,
                            Titulo = "Pago de Servicios"
                        },
                        new
                        {
                            TareaId = new Guid("f5122a67-dc4c-491c-ae01-4408e4841900"),
                            CategoriaId = new Guid("f5122a67-dc4c-491c-ae01-4408e4841902"),
                            FechaCreacion = new DateTime(2023, 11, 12, 0, 1, 6, 284, DateTimeKind.Local).AddTicks(1292),
                            PrioridadTarea = 0,
                            Titulo = "Pago de S"
                        });
                });

            modelBuilder.Entity("proyecto.Models.Tarea", b =>
                {
                    b.HasOne("proyecto.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyecto.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
